import integral_representations_constructed_kernels_e_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace integral_representations_constructed_kernels_e_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end integral_representations_constructed_kernels_e_lemma_canonical_lane_mathlib
end HautevilleHouse
